#pragma once
#include <Arduino.h>

enum class AppState : uint8_t { BOOT, MENU, QUICK_INTRO, QUICK_WAIT, QUICK_GO, QUICK_FEEDBACK, QUICK_SUMMARY,
  FOCUS_INTRO, FOCUS_WAIT, FOCUS_GO, FOCUS_SUMMARY, CHOICE_INTRO, CHOICE_WAIT, CHOICE_GO, CHOICE_SUMMARY,
  RHYTHM_INTRO, RHYTHM_RUNNING, RHYTHM_SUMMARY, MEMORY_INTRO, MEMORY_SHOW, MEMORY_INPUT, MEMORY_FEEDBACK,
  MEMORY_SUMMARY, STATS, SETTINGS, ABOUT, CONFIRM_RESET };
enum class InputEvent : uint8_t { NONE, UP, DOWN, LEFT, RIGHT, SELECT, BACK, START, MENU };
enum class TestKind : uint8_t { QUICK, FOCUS, CHOICE, RHYTHM, MEMORY };
